version: "0.2"
words:
  - armv
  - autoupdate
  - binstall
  - bndy
  - chrono
  - clippy
  - cooldown
  - endfor
  - endgroup
  - endmacro
  - envie
  - FQBN
  - gnueabi
  - gnueabihf
  - hustcer
  - mbed
  - MIDIUSB
  - mkrgsm
  - mkrzero
  - msvc
  - nextest
  - nushell
  - orhun
  - pipx
  - portenta
  - pwsh
  - reqwest
  - rustup
  - samd
  - serde
  - srcset
  - startswith
  - thiserror
  - timeit
  - tlsv
  - topo
  - zizmor
ignorePaths:
  - .gitattributes
  - .gitignore
